### PR TITLE
Update for node 12

### PR DESCRIPTION
**Pull request by spion**
Attempted to fix the module to make it build with newest NaN and node v12.

Wonder if its possible to setup a Travis matrix to run tests on various different node versions.

### CODE REVIEW

**Comment by spion** [comment]
Travis build https://travis-ci.org/spion/node-systemd-journald/builds/527902321

**Comment by jue89** [comment]
Thank you for your contribution! :)
Will have a closer look on your PR within the next days.

**Comment by jue89** [comment]
Sry for the delayed response.

I tested some compatibility. All in all everything looks good to me. But I am not able to run the module on Node 0.10 and 0.12. I know they are dinosaurs but I am looking for a quick solution to make the module working on these versions, as well. The stats are showing that the module has several hundred downloads per week.  Thus, keeping as much compatibility as possible is a good thing in my opinion ...

**Comment by spion** [comment]
Would bumping semver-major to 2.0 be acceptable? Users of older node would continue to use the 1.x version which works perfectly fine...

**Comment by spion** [comment]
I believe the latest build will work down to 0.10:
 
https://travis-ci.org/spion/node-systemd-journald

**Comment by jue89** [comment]
Wow! You rock! :)
Thank you for your effort put into this PR.
I think this should be ready to merge. I will test again and merge tonight.

**Comment by jue89** [comment]
And merged ... thank you again!

**Pull request merged**
